use crate::ast::*;
use crate::error::ArasError;

/// The result of transpilation.
#[derive(Debug, Clone)]
pub struct TranspileOutput {
    /// Ready-to-write `.d2` file content.
    pub d2_source: String,
    /// Resolved D2 theme index (pass as `--theme=N` to d2 CLI).
    pub theme_index: u32,
    /// Diagram type hint (architecture, sequence, erd, …)
    pub diagram_type: String,
}

/// Transpile a parsed [`Diagram`] into D2 source + metadata.
pub fn transpile(diagram: &Diagram) -> Result<TranspileOutput, ArasError> {
    let theme_index = resolve_theme(diagram);
    let diagram_type = resolve_type(diagram);

    let mut out = String::new();

    // Header comment so the file is self-documenting
    out.push_str("# Generated by aras-dsl — ARASKOVA Labs\n");
    out.push_str(&format!("# diagram_type: {}\n\n", diagram_type));

    let mut ctx = EmitCtx { depth: 0, async_edges: Vec::new() };
    emit_stmts(&diagram.stmts, &mut out, &mut ctx);

    // Emit async edge style overrides (dashed) after the main body
    if !ctx.async_edges.is_empty() {
        out.push('\n');
        for (from, to, idx) in &ctx.async_edges {
            let edge_id = format!("{} -> {}", sanitize(from), sanitize(to));
            // D2 allows addressing a specific connection by its order
            out.push_str(&format!(
                "({})[{}].style.stroke-dash: 5\n",
                edge_id, idx
            ));
        }
    }

    Ok(TranspileOutput { d2_source: out, theme_index, diagram_type })
}

// ── Context ───────────────────────────────────────────────────────────────────

struct EmitCtx {
    depth: usize,
    /// Tracks async edges for post-hoc style injection: (from, to, occurrence_idx)
    async_edges: Vec<(String, String, usize)>,
}

impl EmitCtx {
    fn indent(&self) -> String {
        "  ".repeat(self.depth)
    }
}

// ── Emit helpers ──────────────────────────────────────────────────────────────

fn emit_stmts(stmts: &[Stmt], out: &mut String, ctx: &mut EmitCtx) {
    for stmt in stmts {
        emit_stmt(stmt, out, ctx);
    }
}

fn emit_stmt(stmt: &Stmt, out: &mut String, ctx: &mut EmitCtx) {
    let ind = ctx.indent();
    match stmt {
        Stmt::Node(id) => {
            out.push_str(&format!("{}{}\n", ind, sanitize(&id.0)));
        }

        Stmt::NodeDecl(id, label) => {
            out.push_str(&format!(
                "{}{}: \"{}\"\n",
                ind,
                sanitize(&id.0),
                escape_d2(label)
            ));
        }

        Stmt::NodeAttr(attr) => {
            out.push_str(&format!(
                "{}{}.{}: {}\n",
                ind,
                sanitize(&attr.node.0),
                attr.key,
                attr.value.trim()
            ));
        }

        Stmt::Connection(conn) => {
            let from = sanitize(&conn.from.0);
            let to   = sanitize(&conn.to.0);
            let arrow = match conn.arrow {
                Arrow::Directed       => "->",
                Arrow::Reverse        => "<-",
                Arrow::Bidirectional  => "<->",
                Arrow::Undirected     => "--",
                Arrow::Async          => "->", // dashed via style override
            };

            if let Arrow::Async = conn.arrow {
                // record for post-hoc style injection
                let idx = ctx.async_edges.iter()
                    .filter(|(f, t, _)| f == &from && t == &to)
                    .count();
                ctx.async_edges.push((from.clone(), to.clone(), idx));
            }

            match &conn.label {
                Some(label) => out.push_str(&format!(
                    "{}{} {} {}: {}\n",
                    ind, from, arrow, to, label.trim()
                )),
                None => out.push_str(&format!(
                    "{}{} {} {}\n",
                    ind, from, arrow, to
                )),
            }
        }

        Stmt::Group(group) => {
            // D2 groups are just containers: "label": { ... }
            let group_id = to_d2_id(&group.label);
            out.push_str(&format!("{}{}: \"{}\"\n", ind, group_id, escape_d2(&group.label)));
            out.push_str(&format!("{}{}: {{\n", ind, group_id));
            ctx.depth += 1;
            emit_stmts(&group.stmts, out, ctx);
            ctx.depth -= 1;
            out.push_str(&format!("{}}}\n", ind));
        }

        Stmt::Style(block) => {
            let node = sanitize(&block.node.0);
            for prop in &block.props {
                // Map common CSS-like props to D2 style keys
                let d2_key = map_style_key(&prop.key);
                out.push_str(&format!(
                    "{}{}.style.{}: {}\n",
                    ind, node, d2_key, prop.value.trim()
                ));
            }
        }
    }
}

// ── String utilities ──────────────────────────────────────────────────────────

/// D2 identifiers can't have hyphens in all positions — sanitize to underscore.
fn sanitize(id: &str) -> String {
    // D2 actually allows hyphens in identifiers, but let's normalise spaces
    id.replace(' ', "_")
}

/// Convert a human label to a D2-safe identifier.
fn to_d2_id(label: &str) -> String {
    label
        .to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

/// Escape double-quotes inside D2 string literals.
fn escape_d2(s: &str) -> String {
    s.replace('"', "\\\"")
}

/// Map Aras/CSS style keys to D2's style property names.
fn map_style_key(key: &str) -> &str {
    match key {
        "fill"         => "fill",
        "stroke"       => "stroke",
        "color"        => "font-color",
        "font-color"   => "font-color",
        "font-size"    => "font-size",
        "border-radius"=> "border-radius",
        "opacity"      => "opacity",
        "shadow"       => "shadow",
        "bold"         => "bold",
        "italic"       => "italic",
        "underline"    => "underline",
        other          => other,   // pass through unknown keys
    }
}

// ── Theme resolution ──────────────────────────────────────────────────────────

fn resolve_theme(diagram: &Diagram) -> u32 {
    let theme = meta_value(diagram, "theme").unwrap_or_default();
    match theme.to_lowercase().as_str() {
        "default" | "light"      => 0,
        "neutral"                => 200,
        "midnight" | "dark"      => 200, // closest D2 dark equivalent
        "earth"                  => 5,
        "terminal"               => 101,
        "sketch" | "hand"        => 0,   // --sketch flag is separate
        _                        => 200, // aras default: neutral/clean
    }
}

fn resolve_type(diagram: &Diagram) -> String {
    meta_value(diagram, "type")
        .unwrap_or_else(|| "architecture".to_string())
}

fn meta_value(diagram: &Diagram, key: &str) -> Option<String> {
    diagram.meta.iter()
        .find(|m| m.key.eq_ignore_ascii_case(key))
        .map(|m| m.value.clone())
}
